[FIREBALL]
DRAW-TEXTURE = "./assets/sprites/character/gentleman_sheet.png"
POSITION-X = 300
POSITION-Y = 220
VELOCITY-X = 2
VELOCITY-Y = 2
DRAW-SIZE_X = 400
DRAW-SIZE_Y = 580
ANIMATION-STATIC-RECT = [ 0, 126, 55, 63]
ANIMATION-STATIC-X_ADD = 64
ANIMATION-STATIC-NB_FRAME = 7
ANIMATION-STATIC-SPEED = 150555
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 9
ANIMATION-LEFT-SPEED = 65555
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 9
ANIMATION-UP-SPEED = 65555
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 9
ANIMATION-RIGHT-SPEED = 65555
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 9
ANIMATION-DOWN-SPEED = 65555
COLLISION-TYPE = 1
COLLISION-WIDTH = 25
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 0
INTERACTION_ZONE-RADIUS = 100
GAME_MODE-MODE = 0
TEMPORARY-TIME = 10
DAMAGE-DAMAGE = 1
