[FIREBALL]
DRAW-TEXTURE = "./assets/sprites/light_spell.png"
POSITION-X = 8000
POSITION-Y = 8000
VELOCITY-X = 3
VELOCITY-Y = 3
DRAW-SIZE_X = 1920
DRAW-SIZE_Y = 32
ANIMATION-STATIC-RECT = [ 0, 0, 64, 64]
ANIMATION-STATIC-X_ADD = 64
ANIMATION-STATIC-NB_FRAME = 60
ANIMATION-STATIC-SPEED = 16666
ANIMATION-LEFT-RECT = [ 0, 0, 64, 64]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 60
ANIMATION-LEFT-SPEED = 16666
ANIMATION-UP-RECT = [ 0, 0, 64, 64]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 60
ANIMATION-UP-SPEED = 16666
ANIMATION-RIGHT-RECT = [ 0, 0, 64, 64]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 60
ANIMATION-RIGHT-SPEED = 16666
ANIMATION-DOWN-RECT = [ 0, 0, 64, 64]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 60
ANIMATION-DOWN-SPEED = 16666
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 11
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 0
INTERACTION_ZONE-RADIUS = 100
TEMPORARY-TIME = 4
GAME_MODE-MODE = 1
DAMAGE-DAMAGE = 15
