
[PLAYER]
DRAW-TEXTURE = "./assets/sprites/player_sheet.png"
POSITION-X = 200
POSITION-Y = 200
VELOCITY-X = 10
VELOCITY-Y = 10
DRAW-SIZE_X = 300
DRAW-SIZE_Y = 480
ANIMATION-STATIC-RECT = [ 0, 126, 61, 63]
ANIMATION-LEFT-RECT = [ 10, 567, 64, 63]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 9
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 9
ANIMATION-RIGHT-RECT = [ 10, 693, 64, 63]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 9
ANIMATION-DOWN-RECT = [ 10, 630, 64, 63]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 9
