[PLAYER]
DRAW-TEXTURE = "./assets/sprites/character/player_sheet.png"
GAME_MODE-MODE = 1
POSITION-X = 500
POSITION-Y = 150
VELOCITY-X = 10
VELOCITY-Y = 10
DRAW-SIZE_X = 300
DRAW-SIZE_Y = 480
ANIMATION-STATIC-RECT = [ 0, 126, 61, 63]
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 9
ANIMATION-LEFT-SPEED = 65555
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 9
ANIMATION-UP-SPEED = 65555
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 9
ANIMATION-RIGHT-SPEED = 65555
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 9
ANIMATION-DOWN-SPEED = 65555
COLLISION-TYPE = 1
COLLISION-WIDTH = 25
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 0
HEALTH-LIFE = 7
HEALTH-ARMOR = 2
HEALTH-BAR_SIZE_X = 30
HEALTH-BAR_SIZE_Y = 1
INVENTORY-SIZE = 35
