
[TREE]
POSITION-X = 100
POSITION-Y = 120
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
POSITION-X = 240
POSITION-Y = 140
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
POSITION-X = 550
POSITION-Y = 330
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
POSITION-X = 550
POSITION-Y = 190
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
POSITION-X = 420
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 28
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[RED FLOWER]
POSITION-X = 340
POSITION-Y = 250
DRAW-TEXTURE = "./assets/sprites/flower.png"
DRAW-SIZE_X = 13
DRAW-SIZE_Y = 30

[BLUE FLOWER]
POSITION-X = 360
POSITION-Y = 250
DRAW-TEXTURE = "./assets/sprites/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[RED FLOWER]
POSITION-X = 370
POSITION-Y = 365
DRAW-TEXTURE = "./assets/sprites/flower.png"
DRAW-SIZE_X = 13
DRAW-SIZE_Y = 30

[BLUE FLOWER]
POSITION-X = 420
POSITION-Y = 510
DRAW-TEXTURE = "./assets/sprites/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[BLUE FLOWER]
POSITION-X = 555
POSITION-Y = 494
DRAW-TEXTURE = "./assets/sprites/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[GRASS]
POSITION-X = 570
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[GRASS]
POSITION-X = 550
POSITION-Y = 470
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[GRASS]
POSITION-X = 615
POSITION-Y = 470
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[RED FLOWER]
POSITION-X = 590
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/flower.png"
DRAW-SIZE_X = 13
DRAW-SIZE_Y = 30

[BLUE FLOWER]
POSITION-X = 600
POSITION-Y = 499
DRAW-TEXTURE = "./assets/sprites/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[GARDEN]
POSITION-X = 770
POSITION-Y = 470
DRAW-TEXTURE = "./assets/sprites/garden.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 70

[GARDEN]
POSITION-X = 805
POSITION-Y = 505
DRAW-TEXTURE = "./assets/sprites/garden.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 70


[GARDEN]
POSITION-X = 770
POSITION-Y = 505
DRAW-TEXTURE = "./assets/sprites/green_garden.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 70

[GARDEN]
POSITION-X = 805
POSITION-Y = 470
DRAW-TEXTURE = "./assets/sprites/green_garden.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 70

[SHOVEL]
POSITION-X = 835
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/shovel.png"
DRAW-SIZE_X = 25
DRAW-SIZE_Y = 45

[SEED BAG]
POSITION-X = 740
POSITION-Y = 510
DRAW-TEXTURE = "./assets/sprites/seed_bag.png"
DRAW-SIZE_X = 25
DRAW-SIZE_Y = 35
COLLISION-TYPE = 1
COLLISION-WIDTH = 4
COLLISION-HEIGHT = 2
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 1

[GRASS]
POSITION-X = 570
POSITION-Y = 200
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[GRASS]
POSITION-X = 520
POSITION-Y = 190
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[GRASS]
POSITION-X = 240
POSITION-Y = 320
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[GRASS]
POSITION-X = 470
POSITION-Y = 210
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[GRASS]
POSITION-X = 440
POSITION-Y = 180
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[GRASS]
POSITION-X = 230
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[COLLISION]
POSITION-X = 950
POSITION-Y = 0
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 650
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 903
POSITION-Y = 650
COLLISION-TYPE = 1
COLLISION-WIDTH = 30
COLLISION-HEIGHT = 500
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 200
POSITION-Y = 750
COLLISION-TYPE = 1
COLLISION-WIDTH = 1000
COLLISION-HEIGHT = 20
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 0
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 200
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 200
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 400
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 400
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 600
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 600
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 800
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 800
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 1000
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 1000
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 1200
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 1200
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 1400
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 1400
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 1600
POSITION-Y = -75
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 1600
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 200
COLLISION-HEIGHT = 85
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 20
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/rock_wall_side.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 200
COLLISION-TYPE = 1
COLLISION-WIDTH = 185
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 20
POSITION-Y = 200
DRAW-TEXTURE = "./assets/sprites/rock_wall_side.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 200
COLLISION-TYPE = 1
COLLISION-WIDTH = 185
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 20
POSITION-Y = 400
DRAW-TEXTURE = "./assets/sprites/rock_wall_side.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 200
COLLISION-TYPE = 1
COLLISION-WIDTH = 185
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 20
POSITION-Y = 600
DRAW-TEXTURE = "./assets/sprites/rock_wall_side.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 200
COLLISION-TYPE = 1
COLLISION-WIDTH = 185
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
POSITION-X = 20
POSITION-Y = 800
DRAW-TEXTURE = "./assets/sprites/rock_wall_side.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 200
COLLISION-TYPE = 1
COLLISION-WIDTH = 185
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1


[TEST]
POSITION-X = 0
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
INTERACTION_ZONE-RADIUS = 200
VELOCITY-X = 5
VELOCITY-Y = 5
DAMAGE-DAMAGE = 1
COLLISION-TYPE = 1
COLLISION-WIDTH = 50
COLLISION-HEIGHT = 50
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0

