[HOUSE]
POSITION-X = 450
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 75
COLLISION-TYPE = 1
COLLISION-WIDTH = 60
COLLISION-HEIGHT = 42
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[WARP IN]
POSITION-X = 495
POSITION-Y = 350
COLLISION-TYPE = 1
COLLISION-WIDTH = 5
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 3660
WARP-Y = 270
WARP-SOUND = "./assets/sounds/door.wav"

[WARP OUT]
POSITION-X = 3650
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house_floor_exit.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 50
COLLISION-HEIGHT = 43
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 480
WARP-Y = 360
WARP-SOUND = "./assets/sounds/door.wav"

[TOILET]
POSITION-X = 3763
POSITION-Y = 92
DRAW-TEXTURE = "./assets/sprites/blue_toilet.png"
DRAW-SIZE_X = 25
DRAW-SIZE_Y = 25
COLLISION-TYPE = 1
COLLISION-WIDTH = 1
COLLISION-HEIGHT = 25
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[BED]
POSITION-X = 3600
POSITION-Y = 190
DRAW-TEXTURE = "./assets/sprites/red_bed.png"
DRAW-SIZE_X = 25
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 15
COLLISION-HEIGHT = 53
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[DESK]
POSITION-X = 3775
POSITION-Y = 220
DRAW-TEXTURE = "./assets/sprites/desk.png"
DRAW-SIZE_X = 25
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 15
COLLISION-HEIGHT = 33
COLLISION-OFFSET_X = 7
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3600
POSITION-Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 140
COLLISION-HEIGHT = 118
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3580
POSITION-Y = 180
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3805
POSITION-Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 350
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3580
POSITION-Y = 300
COLLISION-TYPE = 1
COLLISION-WIDTH = 60
COLLISION-HEIGHT = 400
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3705
POSITION-Y = 300
COLLISION-TYPE = 1
COLLISION-WIDTH = 80
COLLISION-HEIGHT = 38
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3705
POSITION-Y = 63
COLLISION-TYPE = 1
COLLISION-WIDTH = 80
COLLISION-HEIGHT = 38
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1
