[HOUSE]
POSITION-X = 335
POSITION-Y = 475
DRAW-TEXTURE = "./assets/sprites/house.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 75
COLLISION-TYPE = 1
COLLISION-WIDTH = 60
COLLISION-HEIGHT = 42
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[WARP IN]
POSITION-X = 385
POSITION-Y = 525
COLLISION-TYPE = 1
COLLISION-WIDTH = 1
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 4100
WARP-Y = 270
WARP-SOUND = "./assets/sounds/door.wav"

[WARP OUT]
POSITION-X = 4090
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house_floor_exit.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 50
COLLISION-HEIGHT = 42
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 365
WARP-Y = 535
WARP-SOUND = "./assets/sounds/door.wav"

[PAPER]
POSITION-X = 4100
POSITION-Y = 185
DRAW-TEXTURE = "./assets/sprites/paper.png"
DRAW-SIZE_X = 12
DRAW-SIZE_Y = 30

[COLLISION]
POSITION-X = 4040
POSITION-Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 250
COLLISION-HEIGHT = 105
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 4003
POSITION-Y = 180
COLLISION-TYPE = 1
COLLISION-WIDTH = 35
COLLISION-HEIGHT = 70
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 4303
POSITION-Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 4000
POSITION-Y = 300
COLLISION-TYPE = 1
COLLISION-WIDTH = 80
COLLISION-HEIGHT = 38
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 4205
POSITION-Y = 250
COLLISION-TYPE = 1
COLLISION-WIDTH = 150
COLLISION-HEIGHT = 100
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 4145
POSITION-Y = 300
COLLISION-TYPE = 1
COLLISION-WIDTH = 80
COLLISION-HEIGHT = 38
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 4145
POSITION-Y = 63
COLLISION-TYPE = 1
COLLISION-WIDTH = 80
COLLISION-HEIGHT = 38
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3980
POSITION-Y = 200
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 162
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1
