[HOUSE]
POSITION-X = 300
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 75
COLLISION-TYPE = 1
COLLISION-WIDTH = 60
COLLISION-HEIGHT = 42
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[WARP IN]
POSITION-X = 340
POSITION-Y = 350
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 3255
WARP-Y = 270
WARP-SOUND = "./assets/sounds/door.wav"

[WARP OUT]
POSITION-X = 3250
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house_floor_exit.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 50
COLLISION-HEIGHT = 43
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 330
WARP-Y = 360
WARP-SOUND = "./assets/sounds/door.wav"

[BED]
POSITION-X = 3200
POSITION-Y = 190
DRAW-TEXTURE = "./assets/sprites/cat_bed.png"
DRAW-SIZE_X = 25
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 15
COLLISION-HEIGHT = 53
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[CLOSET]
POSITION-X = 3300
POSITION-Y = 180
DRAW-TEXTURE = "./assets/sprites/closet.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 35
COLLISION-HEIGHT = 43
COLLISION-OFFSET_X = 3
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3200
POSITION-Y = 180
COLLISION-TYPE = 1
COLLISION-WIDTH = 300
COLLISION-HEIGHT = 23
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3180
POSITION-Y = 180
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3355
POSITION-Y = 180
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 200
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLLISION]
POSITION-X = 3180
POSITION-Y = 300
COLLISION-TYPE = 1
COLLISION-WIDTH = 60
COLLISION-HEIGHT = 38
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1


[COLLISION]
POSITION-X = 3305
POSITION-Y = 300
COLLISION-TYPE = 1
COLLISION-WIDTH = 60
COLLISION-HEIGHT = 38
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1