[PLAY]
GAME_MODE-MODE = 0
POSITION-X = 100
POSITION-Y = 180
DRAW-TEXTURE = "./assets/sprites/menu/button.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
CLICKABLE-STATE = 0
CLICKABLE-CALLBACK = "PLAY-BUTTON"

[BACKGROUND]
GAME_MODE-MODE = 0
POSITION-X = -50
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/menu/menu.jpg"
DRAW-SIZE_X = 400
DRAW-SIZE_Y = 270

[PLAY]
GAME_MODE-MODE = 0
POSITION-X = 50
POSITION-Y = 80
DRAW-TEXTURE = "./assets/sprites/menu/name.png"
DRAW-SIZE_X = 200
DRAW-SIZE_Y = 50