
[TREE]
POSITION-X = 100
POSITION-Y = 120
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
POSITION-X = 200
POSITION-Y = 140
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
POSITION-X = 550
POSITION-Y = 330
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
POSITION-X = 550
POSITION-Y = 190
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
POSITION-X = 420
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[RED FLOWER]
POSITION-X = 340
POSITION-Y = 250
DRAW-TEXTURE = "./assets/sprites/flower.png"
DRAW-SIZE_X = 13
DRAW-SIZE_Y = 30

[BLUE FLOWER]
POSITION-X = 360
POSITION-Y = 250
DRAW-TEXTURE = "./assets/sprites/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[RED FLOWER]
POSITION-X = 370
POSITION-Y = 365
DRAW-TEXTURE = "./assets/sprites/flower.png"
DRAW-SIZE_X = 13
DRAW-SIZE_Y = 30

[BLUE FLOWER]
POSITION-X = 420
POSITION-Y = 510
DRAW-TEXTURE = "./assets/sprites/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30