
[HOUSE]
POSITION-X = 300
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 75
COLLISION-TYPE = 1
COLLISION-WIDTH = 60
COLLISION-HEIGHT = 35
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 1

[WARP IN]
POSITION-X = 340
POSITION-Y = 350
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 2
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 3255
WARP-Y = 270
WARP-SOUND = "./assets/sounds/door.wav"

[WARP OUT]
POSITION-X = 3250
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house_floor_exit.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 50
COLLISION-HEIGHT = 25
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 330
WARP-Y = 370
WARP-SOUND = "./assets/sounds/door.wav"


[HOUSE]
POSITION-X = 450
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 75
COLLISION-TYPE = 1
COLLISION-WIDTH = 60
COLLISION-HEIGHT = 35
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 1

[WARP IN]
POSITION-X = 490
POSITION-Y = 350
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 2
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 3660
WARP-Y = 270
WARP-SOUND = "./assets/sounds/door.wav"

[WARP OUT]
POSITION-X = 3650
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/house_floor_exit.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 50
COLLISION-HEIGHT = 25
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 480
WARP-Y = 370
WARP-SOUND = "./assets/sounds/door.wav"