

[TEST]
POSITION-X = 400
POSITION-Y = 400
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 0
COLLISION-RADIUS = 25
WARP-X = 3255
WARP-Y = 270
WARP-SOUND = "./assets/sounds/door.wav"

[TEST]
POSITION-X = 3255
POSITION-Y = 320
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 0
COLLISION-RADIUS = 25
WARP-X = 100
WARP-Y = 100
WARP-SOUND = "./assets/sounds/door.wav"

[TEST]
POSITION-X = 0
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
<<<<<<< Updated upstream
DRAW-SIZE_Y = 50
VELOCITY-X = 5
VELOCITY-Y = 5
INTERACTION_ZONE-RADIUS = 300
COLLISION-TYPE = 0
COLLISION-RADIUS = 25
DAMAGE-DAMAGE = 4
=======
DRAW-SIZE_Y = 300
VELOCITY-X = 0
VELOCITY-Y = 0

[TEST]
POSITION-X = 0
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
GAME_MODE-MODE = 0
VELOCITY-X = 0
VELOCITY-Y = 0
>>>>>>> Stashed changes
