[PLAYER]
POSITION-X = 0
POSITION-Y = 100
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 60
DRAW-SIZE_Y = 60
VELOCITY-X = 10
VELOCITY-Y = 10

[TEST]
POSITION-X = 0
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
VELOCITY-X = 0
VELOCITY-Y = 0

[TEST]
POSITION-X = 0
POSITION-Y = 200
DRAW-TEXTURE = "./assets/sprites/grass.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
VELOCITY-X = 0
VELOCITY-Y = 0

[TEST]
POSITION-X = -50
POSITION-Y = 200
DRAW-TEXTURE = "./assets/sprites/grass.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
VELOCITY-X = 0
VELOCITY-Y = 0

[TEST]
POSITION-X = 200
POSITION-Y = 32
DRAW-TEXTURE = "./assets/sprites/grass.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
VELOCITY-X = 0
VELOCITY-Y = 0
