
[TEST]
POSITION-X = 0
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
VELOCITY-X = 0
VELOCITY-Y = 0

[TEST]
POSITION-X = 0
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
VELOCITY-X = 0
VELOCITY-Y = 0

[TEST]
POSITION-X = 0
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
VELOCITY-X = 0
VELOCITY-Y = 0

[TEST]
POSITION-X = 0
POSITION-Y = 0
DRAW-TEXTURE = "./assets/sprites/player.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
VELOCITY-X = 0
VELOCITY-Y = 0
