

[RED FLOWER]
GAME_MODE-MODE = 1
POSITION-X = 340
POSITION-Y = 250
DRAW-TEXTURE = "./assets/sprites/exterior/flower.png"
DRAW-SIZE_X = 13
DRAW-SIZE_Y = 30

[BLUE FLOWER]
GAME_MODE-MODE = 1
POSITION-X = 360
POSITION-Y = 250
DRAW-TEXTURE = "./assets/sprites/exterior/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[RED FLOWER]
GAME_MODE-MODE = 1
POSITION-X = 370
POSITION-Y = 365
DRAW-TEXTURE = "./assets/sprites/exterior/flower.png"
DRAW-SIZE_X = 13
DRAW-SIZE_Y = 30

[BLUE FLOWER]
GAME_MODE-MODE = 1
POSITION-X = 420
POSITION-Y = 510
DRAW-TEXTURE = "./assets/sprites/exterior/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[BLUE FLOWER]
GAME_MODE-MODE = 1
POSITION-X = 555
POSITION-Y = 494
DRAW-TEXTURE = "./assets/sprites/exterior/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 570
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 550
POSITION-Y = 470
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 615
POSITION-Y = 470
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[RED FLOWER]
GAME_MODE-MODE = 1
POSITION-X = 590
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/exterior/flower.png"
DRAW-SIZE_X = 13
DRAW-SIZE_Y = 30

[BLUE FLOWER]
GAME_MODE-MODE = 1
POSITION-X = 600
POSITION-Y = 499
DRAW-TEXTURE = "./assets/sprites/exterior/blue_flower.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 30

[GARDEN]
GAME_MODE-MODE = 1
POSITION-X = 770
POSITION-Y = 470
DRAW-TEXTURE = "./assets/sprites/exterior/garden.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 70

[GARDEN]
GAME_MODE-MODE = 1
POSITION-X = 805
POSITION-Y = 505
DRAW-TEXTURE = "./assets/sprites/exterior/garden.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 70


[GARDEN]
GAME_MODE-MODE = 1
POSITION-X = 770
POSITION-Y = 505
DRAW-TEXTURE = "./assets/sprites/exterior/green_garden.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 70

[GARDEN]
GAME_MODE-MODE = 1
POSITION-X = 805
POSITION-Y = 470
DRAW-TEXTURE = "./assets/sprites/exterior/green_garden.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 70

[SHOVEL]
GAME_MODE-MODE = 1
POSITION-X = 835
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/object/shovel.png"
DRAW-SIZE_X = 25
DRAW-SIZE_Y = 45

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 570
POSITION-Y = 200
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 520
POSITION-Y = 190
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 240
POSITION-Y = 320
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 470
POSITION-Y = 210
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 440
POSITION-Y = 180
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70

[GRASS]
GAME_MODE-MODE = 1
POSITION-X = 230
POSITION-Y = 300
DRAW-TEXTURE = "./assets/sprites/exterior/grass_texture.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 70


