[PNG GENTLEMAN]
DRAW-TEXTURE = "./assets/sprites/character/gentleman_sheet.png"
GAME_MODE-MODE = 1
POSITION-X = 300
POSITION-Y = 200
VELOCITY-X = 3
VELOCITY-Y = 3
DRAW-SIZE_X = 400
DRAW-SIZE_Y = 580
ANIMATION-STATIC-RECT = [ 0, 126, 55, 63]
ANIMATION-STATIC-X_ADD = 64
ANIMATION-STATIC-NB_FRAME = 7
ANIMATION-STATIC-SPEED = 150555
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 9
ANIMATION-LEFT-SPEED = 65555
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 9
ANIMATION-UP-SPEED = 65555
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 9
ANIMATION-RIGHT-SPEED = 65555
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 9
ANIMATION-DOWN-SPEED = 65555
COLLISION-TYPE = 1
COLLISION-WIDTH = 25
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 0
HEALTH-LIFE = 3
HEALTH-ARMOR = 2
HEALTH-BAR_SIZE_X = 17
HEALTH-BAR_SIZE_Y = 1
INTERACTION_ZONE-RADIUS = 20
TEXT-SIZE = 10
TEXT-CONTENT = "Bonjour etranger"
TEXT-FONT = "./assets/font/Milker.otf"

[PNG KNIGHT]
DRAW-TEXTURE = "./assets/sprites/character/knight_sheet.png"
GAME_MODE-MODE = 1
POSITION-X = 500
POSITION-Y = 200
VELOCITY-X = 3
VELOCITY-Y = 3
DRAW-SIZE_X = 400
DRAW-SIZE_Y = 580
ANIMATION-STATIC-RECT = [ 0, 126, 55, 63]
ANIMATION-STATIC-X_ADD = 64
ANIMATION-STATIC-NB_FRAME = 7
ANIMATION-STATIC-SPEED = 150555
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 9
ANIMATION-LEFT-SPEED = 65555
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 9
ANIMATION-UP-SPEED = 65555
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 9
ANIMATION-RIGHT-SPEED = 65555
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 9
ANIMATION-DOWN-SPEED = 65555
COLLISION-TYPE = 1
COLLISION-WIDTH = 25
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 0
HEALTH-LIFE = 3
HEALTH-ARMOR = 2
HEALTH-BAR_SIZE_X = 17
HEALTH-BAR_SIZE_Y = 1
INTERACTION_ZONE-RADIUS = 20
TEXT-SIZE = 10
TEXT-CONTENT = "il me faut de la viande"
TEXT-FONT = "./assets/font/Milker.otf"

[COOKIE GRANDMA]
DRAW-TEXTURE = "./assets/sprites/character/cookie_grandma.png"
GAME_MODE-MODE = 1
POSITION-X = 3250
POSITION-Y = 200
DRAW-SIZE_X = 500
DRAW-SIZE_Y = 40
VELOCITY-X = 0
VELOCITY-Y = 0
ANIMATION-STATIC-RECT = [ 0, 0, 252, 252]
ANIMATION-STATIC-X_ADD = 256
ANIMATION-STATIC-NB_FRAME = 16
ANIMATION-STATIC-SPEED = 250000
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
COLLISION-TYPE = 1
COLLISION-WIDTH = 2
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 11
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1
HEALTH-LIFE = 3
HEALTH-ARMOR = 2
HEALTH-BAR_SIZE_X = 30
HEALTH-BAR_SIZE_Y = 1
INTERACTION_ZONE-RADIUS = 30
TEXT-SIZE = 10
TEXT-CONTENT = "miam les delicieux cookies"
TEXT-FONT = "./assets/font/Milker.otf"

[CRUSADER]
DRAW-TEXTURE = "./assets/sprites/character/crusader_sheet.png"
GAME_MODE-MODE = 1
POSITION-X = 3650
POSITION-Y = 200
DRAW-SIZE_X = 400
DRAW-SIZE_Y = 580
VELOCITY-X = 1
VELOCITY-Y = 1
ANIMATION-STATIC-RECT = [ 0, 126, 55, 63]
ANIMATION-STATIC-X_ADD = 64
ANIMATION-STATIC-NB_FRAME = 7
ANIMATION-STATIC-SPEED = 150555
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 9
ANIMATION-LEFT-SPEED = 65555
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 9
ANIMATION-UP-SPEED = 65555
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 9
ANIMATION-RIGHT-SPEED = 65555
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 9
ANIMATION-DOWN-SPEED = 65555
COLLISION-TYPE = 1
COLLISION-WIDTH = 25
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 0
HEALTH-LIFE = 3
HEALTH-ARMOR = 2
HEALTH-BAR_SIZE_X = 30
HEALTH-BAR_SIZE_Y = 1
INTERACTION_ZONE-RADIUS = 30
TEXT-SIZE = 10
TEXT-CONTENT = "j'ai vendu mes vetements pour m'acheter ce bouclier"
TEXT-FONT = "./assets/font/Milker.otf"
DAMAGE-DAMAGE = 0

[GRANDMA]
DRAW-TEXTURE = "./assets/sprites/character/cookie_grandma.png"
GAME_MODE-MODE = 1
POSITION-X = 3250
POSITION-Y = 200
DRAW-SIZE_X = 500
DRAW-SIZE_Y = 40
VELOCITY-X = 0
VELOCITY-Y = 0
ANIMATION-STATIC-RECT = [ 0, 0, 252, 252]
ANIMATION-STATIC-X_ADD = 256
ANIMATION-STATIC-NB_FRAME = 16
ANIMATION-STATIC-SPEED = 250000
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
COLLISION-TYPE = 1
COLLISION-WIDTH = 2
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 11
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1
HEALTH-LIFE = 3
HEALTH-ARMOR = 2
HEALTH-BAR_SIZE_X = 30
HEALTH-BAR_SIZE_Y = 1
INTERACTION_ZONE-RADIUS = 30
TEXT-SIZE = 10
TEXT-CONTENT = "miam les delicieux cookies"
TEXT-FONT = "./assets/font/Milker.otf"

[WILL SMITH]
DRAW-TEXTURE = "./assets/sprites/character/black_friend.png"
GAME_MODE-MODE = 1
POSITION-X = 650
POSITION-Y = 1750
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 30
COLLISION-TYPE = 1
COLLISION-WIDTH = 1
COLLISION-HEIGHT = 10
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 1
INTERACTION_ZONE-RADIUS = 30
TEXT-SIZE = 10
TEXT-CONTENT = "t'a bien dormi ? t'a pas reve de moi ?"
TEXT-FONT = "./assets/font/Milker.otf"
