
[Kitsune]
DRAW-TEXTURE = "./assets/sprites/character/kitsune.png"
GAME_MODE-MODE = 1
POSITION-X = 3300
POSITION-Y = 550
VELOCITY-X = 0
VELOCITY-Y = 0
DRAW-SIZE_X = 768
DRAW-SIZE_Y = 128
ANIMATION-STATIC-RECT = [ 0, 0, 128, 128]
ANIMATION-STATIC-X_ADD = 128
ANIMATION-STATIC-NB_FRAME = 6
ANIMATION-STATIC-SPEED = 155555
COLLISION-TYPE = 1
COLLISION-WIDTH = 64
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 32
COLLISION-OFFSET_Y = 48
COLLISION-WALL = 0
TEXT-SIZE = 10
INTERACTION_ZONE-RADIUS = 70
TEXT-CONTENT = "choose your weapon !"
TEXT-FONT = "./assets/font/Milker.otf"

[WALL_1]
GAME_MODE-MODE = 1
POSITION-X = 3200
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_stone.png"
DRAW-SIZE_X = 128
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 128
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL_2]
GAME_MODE-MODE = 1
POSITION-X = 3328
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_stone.png"
DRAW-SIZE_X = 128
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 118
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[STAIRS]
GAME_MODE-MODE = 1
POSITION-X = 3456
POSITION-Y = 669
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/stairs.png"
DRAW-SIZE_X = 64
DRAW-SIZE_Y = 127


[STAIRS_collision]
GAME_MODE-MODE = 1
POSITION-X = 3456
POSITION-Y = 700
COLLISION-TYPE = 1
COLLISION-WIDTH = 1
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 1

[STAIRS_collision]
GAME_MODE-MODE = 1
POSITION-X = 3515
POSITION-Y = 700
COLLISION-TYPE = 1
COLLISION-WIDTH = 1
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 1

[WALL_3]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_stone.png"
DRAW-SIZE_X = 128
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 118
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL_4]
GAME_MODE-MODE = 1
POSITION-X = 3648
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_stone.png"
DRAW-SIZE_X = 128
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 118
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL_4]
GAME_MODE-MODE = 1
POSITION-X = 3756
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_window.png"
DRAW-SIZE_X = 44
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 40
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1


[statue]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 805
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/statue.png"
DRAW-SIZE_X = 37
DRAW-SIZE_Y = 70
COLLISION-TYPE = 1
COLLISION-WIDTH = 22
COLLISION-HEIGHT = 40
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1



