
[Kitsune]
DRAW-TEXTURE = "./assets/sprites/character/kitsune.png"
GAME_MODE-MODE = 1
POSITION-X = 3300
POSITION-Y = 600
VELOCITY-X = 0
VELOCITY-Y = 0
DRAW-SIZE_X = 768
DRAW-SIZE_Y = 128
ANIMATION-STATIC-RECT = [ 50, 50, 78, 78]
ANIMATION-STATIC-X_ADD = 128
ANIMATION-STATIC-NB_FRAME = 6
ANIMATION-STATIC-SPEED = 155555
COLLISION-TYPE = 1
COLLISION-WIDTH = 40
COLLISION-HEIGHT = 45
COLLISION-OFFSET_X = 24
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1
TEXT-SIZE = 10
INTERACTION_ZONE-RADIUS = 100
TEXT-CONTENT = "choose your weapon !"
TEXT-FONT = "./assets/font/Milker.otf"

[WALL_1]
GAME_MODE-MODE = 1
POSITION-X = 3200
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_stone.png"
DRAW-SIZE_X = 128
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 128
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL_2]
GAME_MODE-MODE = 1
POSITION-X = 3328
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_stone.png"
DRAW-SIZE_X = 128
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 118
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[STAIRS]
GAME_MODE-MODE = 1
POSITION-X = 3456
POSITION-Y = 669
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/stairs.png"
DRAW-SIZE_X = 64
DRAW-SIZE_Y = 127


[STAIRS_collision]
GAME_MODE-MODE = 1
POSITION-X = 3456
POSITION-Y = 700
COLLISION-TYPE = 1
COLLISION-WIDTH = 1
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 1

[STAIRS_collision]
GAME_MODE-MODE = 1
POSITION-X = 3515
POSITION-Y = 700
COLLISION-TYPE = 1
COLLISION-WIDTH = 1
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 1

[WALL_3]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_stone.png"
DRAW-SIZE_X = 128
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 118
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL_4]
GAME_MODE-MODE = 1
POSITION-X = 3648
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_stone.png"
DRAW-SIZE_X = 128
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 118
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL_4]
GAME_MODE-MODE = 1
POSITION-X = 3756
POSITION-Y = 700
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/wall_window.png"
DRAW-SIZE_X = 44
DRAW-SIZE_Y = 64
COLLISION-TYPE = 1
COLLISION-WIDTH = 40
COLLISION-HEIGHT = 64
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1


[statue]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 805
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/statue.png"
DRAW-SIZE_X = 37
DRAW-SIZE_Y = 70
COLLISION-TYPE = 1
COLLISION-WIDTH = 22
COLLISION-HEIGHT = 40
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[delim left]
GAME_MODE-MODE = 1
POSITION-X = 3300
POSITION-Y = 610
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter.png"
DRAW-SIZE_X = 8
DRAW-SIZE_Y = 96
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 96
COLLISION-OFFSET_X = -12
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[delim left]
GAME_MODE-MODE = 1
POSITION-X = 3300
POSITION-Y = 550
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter.png"
DRAW-SIZE_X = 8
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 100
COLLISION-OFFSET_X = -12
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3300
POSITION-Y = 550
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 96
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 1

[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3396
POSITION-Y = 550
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 96
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 1

[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3492
POSITION-Y = 550
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 96
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 1

[delim right]
GAME_MODE-MODE = 1
POSITION-X = 3588
POSITION-Y = 550
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter.png"
DRAW-SIZE_X = 8
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 100
COLLISION-OFFSET_X = 12
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[delim right]
GAME_MODE-MODE = 1
POSITION-X = 3588
POSITION-Y = 646
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter.png"
DRAW-SIZE_X = 8
DRAW-SIZE_Y = 55
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 55
COLLISION-OFFSET_X = 12
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[table 1]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 565
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/table.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 30
COLLISION-TYPE = 1
COLLISION-WIDTH = 20
COLLISION-HEIGHT = 15
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 5
COLLISION-WALL = 1

[WOND]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 565
DRAW-TEXTURE = "./assets/sprites/object/wond.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 15
COLLISION-TYPE = 1
COLLISION-WIDTH = 25
COLLISION-HEIGHT = 20
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
PICKABLE-BOOL = 1

[table2]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 605
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/table.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 30
COLLISION-TYPE = 1
COLLISION-WIDTH = 20
COLLISION-HEIGHT = 15
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 5
COLLISION-WALL = 1

[RING]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 605
DRAW-TEXTURE = "./assets/sprites/object/ring.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 15
COLLISION-TYPE = 1
COLLISION-WIDTH = 25
COLLISION-HEIGHT = 20
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
PICKABLE-BOOL = 1

[table3]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 650
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/table.png"
DRAW-SIZE_X = 30
DRAW-SIZE_Y = 30
COLLISION-TYPE = 1
COLLISION-WIDTH = 20
COLLISION-HEIGHT = 15
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 5
COLLISION-WALL = 1

[RING]
GAME_MODE-MODE = 1
POSITION-X = 3520
POSITION-Y = 650
DRAW-TEXTURE = "./assets/sprites/object/sword.png"
DRAW-SIZE_X = 15
DRAW-SIZE_Y = 15
COLLISION-TYPE = 1
COLLISION-WIDTH = 25
COLLISION-HEIGHT = 20
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
PICKABLE-BOOL = 1

[delim_left]
GAME_MODE-MODE = 1
POSITION-X = 3200
POSITION-Y = 763
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter.png"
DRAW-SIZE_X = 8
DRAW-SIZE_Y = 137
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 137
COLLISION-OFFSET_X = -12
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3208
POSITION-Y = 892
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 96
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3304
POSITION-Y = 892
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 96
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1


[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3400
POSITION-Y = 892
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 96
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1


[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3496
POSITION-Y = 892
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 96
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1


[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3592
POSITION-Y = 892
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 96
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1


[delim top]
GAME_MODE-MODE = 1
POSITION-X = 3686
POSITION-Y = 892
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter_plat.png"
DRAW-SIZE_X = 114
DRAW-SIZE_Y = 8
COLLISION-TYPE = 1
COLLISION-WIDTH = 114
COLLISION-HEIGHT = 8
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[delim_right down]
GAME_MODE-MODE = 1
POSITION-X = 3792
POSITION-Y = 763
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/delimiter.png"
DRAW-SIZE_X = 8
DRAW-SIZE_Y = 137
COLLISION-TYPE = 1
COLLISION-WIDTH = 8
COLLISION-HEIGHT = 137
COLLISION-OFFSET_X = -12
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[depart zone]
GAME_MODE-MODE = 1
POSITION-X = 3250
POSITION-Y = 750
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/drop_zone.png"
DRAW-SIZE_X = 57
DRAW-SIZE_Y = 100

[to history zone]
GAME_MODE-MODE = 1
POSITION-X = 3400
POSITION-Y = 510
DRAW-TEXTURE = "./assets/sprites/exterior/start_place/drop_zone.png"
DRAW-SIZE_X = 57
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 57
COLLISION-HEIGHT = 57
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 43
COLLISION-WALL = 0
WARP-X = 300
WARP-Y = 200
WARP-SOUND = "./assets/sounds/teleport.wav"

