[TREE]
GAME_MODE-MODE = 1
POSITION-X = 100
POSITION-Y = 120
DRAW-TEXTURE = "./assets/sprites/exterior/mid_tree.png"
DRAW-SIZE_X = 75
DRAW-SIZE_Y = 90
COLLISION-TYPE = 1
COLLISION-WIDTH = 20
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 23
COLLISION-WALL = 1

[TREE]
GAME_MODE-MODE = 1
POSITION-X = 240
POSITION-Y = 140
DRAW-TEXTURE = "./assets/sprites/exterior/mid_tree.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 20
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 23
COLLISION-WALL = 1

[TREE]
GAME_MODE-MODE = 1
POSITION-X = 550
POSITION-Y = 330
DRAW-TEXTURE = "./assets/sprites/exterior/mid_tree.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 20
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 23
COLLISION-WALL = 1


[TREE]
GAME_MODE-MODE = 1
POSITION-X = 550
POSITION-Y = 190
DRAW-TEXTURE = "./assets/sprites/exterior/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[TREE]
GAME_MODE-MODE = 1
POSITION-X = 420
POSITION-Y = 480
DRAW-TEXTURE = "./assets/sprites/exterior/small_tree.png"
DRAW-SIZE_X = 36
DRAW-SIZE_Y = 60
COLLISION-TYPE = 1
COLLISION-WIDTH = 3
COLLISION-HEIGHT = 29
COLLISION-OFFSET_X = 15
COLLISION-OFFSET_Y = 26
COLLISION-WALL = 1

[SEED BAG]
GAME_MODE-MODE = 1
POSITION-X = 740
POSITION-Y = 510
DRAW-TEXTURE = "./assets/sprites/exterior/seed_bag.png"
DRAW-SIZE_X = 25
DRAW-SIZE_Y = 35
COLLISION-TYPE = 1
COLLISION-WIDTH = 4
COLLISION-HEIGHT = 2
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 15
COLLISION-WALL = 1