[KEYS-0]
KEY-UP = "ACTION-UP"
KEY-DOWN = "ACTION-DOWN"
KEY-LEFT = "ACTION-LEFT"
KEY-RIGHT = "ACTION-RIGHT"
KEY-A = "ACTION-ATTACK"

[KEYS-1]
KEY-UP = "ACTION-DOWN"
KEY-DOWN = "ACTION-UP"
KEY-LEFT = "ACTION-LEFT"
KEY-RIGHT = "ACTION-RIGHT"
KEY-A = "ACTION-ATTACK"

[KEYS-2]
KEY-UP = "ACTION-UP"
KEY-DOWN = "ACTION-DOWN"
KEY-LEFT = "ACTION-LEFT"
KEY-RIGHT = "ACTION-RIGHT"
KEY-B = "ACTION-ATTACK"
