[KEYS-0]
KEY-UP = "ACTION-UP"
KEY-DOWN = "ACTION-DOWN"
KEY-LEFT = "ACTION-LEFT"
KEY-RIGHT = "ACTION-RIGHT"
KEY-A = "ACTION-ATTACK"

[KEYS-1]
KEY-Z = "ACTION-UP"
KEY-S = "ACTION-DOWN"
KEY-Q = "ACTION-LEFT"
KEY-D = "ACTION-RIGHT"
KEY-A = "ACTION-ATTACK"
KEY-I = "ACTION-INVENTORY"

[KEYS-2]
KEY-UP = "ACTION-UP"
KEY-DOWN = "ACTION-DOWN"
KEY-LEFT = "ACTION-LEFT"
KEY-RIGHT = "ACTION-RIGHT"
KEY-B = "ACTION-ATTACK"
KEY-I = "ACTION-INVENTORY"
