[GRASS]
SPRITE = "./assets/sprites/exterior/grass.png"
SOUND = "./assets/sounds/grass.wav"
CHAR = "#"

[WATER]
SPRITE = "./assets/sprites/exterior/water.png"
SOUND = "./assets/sounds/water.wav"
CHAR = "~"

[SAND]
SPRITE = "./assets/sprites/exterior/sand.png"
SOUND = "./assets/sounds/sand.wav"
CHAR = "+"

[WOOD]
SPRITE = "./assets/sprites/interior/house_floor.png"
SOUND = "./assets/sounds/wood.wav"
CHAR = "p"

[CAVE]
SPRITE = "./assets/sprites/cave/cave.png"
SOUND = "./assets/sounds/cave.wav"
CHAR = "c"