[ENTRANCE]
GAME_MODE-MODE = 1
POSITION-X = 600
POSITION-Y = 45
DRAW-TEXTURE = "./assets/sprites/cave/cave_entrence.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 45
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 27
COLLISION-WALL = 0
WARP-X = 2500
WARP-Y = 575
WARP-SOUND = "./assets/sounds/cave_warp.wav"

[WARP OUT ENTER]
GAME_MODE-MODE = 1
POSITION-X = 2500
POSITION-Y = 600
DRAW-TEXTURE = "./assets/sprites/cave/cave_exit.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 50
COLLISION-HEIGHT = 43
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 0
WARP-X = 610
WARP-Y = 80
WARP-SOUND = "./assets/sounds/cave_warp.wav"

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2450
POSITION-Y = 454
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 100
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2550
POSITION-Y = 454
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 100
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2650
POSITION-Y = 454
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 100
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2437
POSITION-Y = 460
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2437
POSITION-Y = 530
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2750
POSITION-Y = 454
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 85
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2840
POSITION-Y = 400
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 65
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2900
POSITION-Y = 454
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 85
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 3000
POSITION-Y = 454
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 85
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 3090
POSITION-Y = 460
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 3090
POSITION-Y = 530
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2890
POSITION-Y = 420
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 50
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2890
POSITION-Y = 330
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 140
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 5
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2800
POSITION-Y = 315
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 85
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2720
POSITION-Y = 205
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 80
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 85
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2640
POSITION-Y = 205
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 80
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 85
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2635
POSITION-Y = 211
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 90
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 70
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2790
POSITION-Y = 210
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1


[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2790
POSITION-Y = 280
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 50
COLLISION-OFFSET_X = 5
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2635
POSITION-Y = 350
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 70
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2563
POSITION-Y = 255
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 80
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 85
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2498
POSITION-Y = 255
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 65
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 85
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[COLISION]
GAME_MODE-MODE = 1
POSITION-X = 2550
POSITION-Y = 600
COLLISION-TYPE = 1
COLLISION-WIDTH = 300
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLISION]
GAME_MODE-MODE = 1
POSITION-X = 2850
POSITION-Y = 600
COLLISION-TYPE = 1
COLLISION-WIDTH = 300
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLISION]
GAME_MODE-MODE = 1
POSITION-X = 2450
POSITION-Y = 600
COLLISION-TYPE = 1
COLLISION-WIDTH = 40
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLISION]
GAME_MODE-MODE = 1
POSITION-X = 2000
POSITION-Y = 350
COLLISION-TYPE = 1
COLLISION-WIDTH = 330
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLISION]
GAME_MODE-MODE = 1
POSITION-X = 2330
POSITION-Y = 350
COLLISION-TYPE = 1
COLLISION-WIDTH = 300
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[COLISION]
GAME_MODE-MODE = 1
POSITION-X = 2630
POSITION-Y = 400
COLLISION-TYPE = 1
COLLISION-WIDTH = 220
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 0
COLLISION-WALL = 1

[lava]
GAME_MODE-MODE = 1
DRAW-TEXTURE = "./assets/sprites/cave/lava.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 89
POSITION-X = 2660
POSITION-Y = 205
VELOCITY-X = 0
VELOCITY-Y = 0
ANIMATION-STATIC-RECT = [ 0, 0, 32, 90]
ANIMATION-STATIC-X_ADD = 32
ANIMATION-STATIC-NB_FRAME = 3
ANIMATION-STATIC-SPEED = 250000
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
COLLISION-TYPE = 1
COLLISION-WIDTH = 20
COLLISION-HEIGHT = 32
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 50
COLLISION-WALL = 0
DAMAGE-DAMAGE = 1

[lava]
GAME_MODE-MODE = 1
DRAW-TEXTURE = "./assets/sprites/cave/lava.png"
DRAW-SIZE_X = 96
DRAW-SIZE_Y = 89
POSITION-X = 2692
POSITION-Y = 205
VELOCITY-X = 0
VELOCITY-Y = 0
ANIMATION-STATIC-RECT = [ 0, 0, 32, 90]
ANIMATION-STATIC-X_ADD = 32
ANIMATION-STATIC-NB_FRAME = 3
ANIMATION-STATIC-SPEED = 250000
ANIMATION-LEFT-RECT = [ 10, 577, 64, 63]
ANIMATION-UP-RECT = [ 10, 504, 64, 63]
ANIMATION-RIGHT-RECT = [ 10, 703, 64, 63]
ANIMATION-DOWN-RECT = [ 10, 640, 64, 63]
COLLISION-TYPE = 1
COLLISION-WIDTH = 20
COLLISION-HEIGHT = 32
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 50
COLLISION-WALL = 0
DAMAGE-DAMAGE = 1

[CORNER]
GAME_MODE-MODE = 1
POSITION-X = 2658
POSITION-Y = 240
DRAW-TEXTURE = "./assets/sprites/cave/corner_cave1.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[CORNER]
GAME_MODE-MODE = 1
POSITION-X = 2708
POSITION-Y = 222
DRAW-TEXTURE = "./assets/sprites/cave/corner_cave2.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[CORNER]
GAME_MODE-MODE = 1
POSITION-X = 2708
POSITION-Y = 240
DRAW-TEXTURE = "./assets/sprites/cave/corner_cave3.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[CORNER]
GAME_MODE-MODE = 1
POSITION-X = 2658
POSITION-Y = 222
DRAW-TEXTURE = "./assets/sprites/cave/corner_cave4.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 60

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2200
POSITION-Y = 100
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2400
POSITION-Y = 130
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2700
POSITION-Y = 220
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2600
POSITION-Y = 370
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2800
POSITION-Y = 380
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2950
POSITION-Y = 400
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2100
POSITION-Y = 53
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2140
POSITION-Y = 110
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2140
POSITION-Y = 110
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[DECO]
GAME_MODE-MODE = 1
POSITION-X = 2430
POSITION-Y = 180
DRAW-TEXTURE = "./assets/sprites/cave/cave_deco.png"
DRAW-SIZE_X = 40
DRAW-SIZE_Y = 160

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2040
POSITION-Y = 125
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2040
POSITION-Y = 255
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 100
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2040
POSITION-Y = 105
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 100
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2040
POSITION-Y = 175
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2040
POSITION-Y = 10
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_left.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 100
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 100
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2050
POSITION-Y = 10
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 100
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2150
POSITION-Y = 10
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 100
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2250
POSITION-Y = 10
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 100
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 100
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2350
POSITION-Y = 10
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 75
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 100
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2425
POSITION-Y = 10
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_front.png"
DRAW-SIZE_X = 75
DRAW-SIZE_Y = 50
COLLISION-TYPE = 1
COLLISION-WIDTH = 100
COLLISION-HEIGHT = 22
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2490
POSITION-Y = 15
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2490
POSITION-Y = 95
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 80
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[WALL]
GAME_MODE-MODE = 1
POSITION-X = 2490
POSITION-Y = 175
DRAW-TEXTURE = "./assets/sprites/cave/cave_wall_side_right.png"
DRAW-SIZE_X = 20
DRAW-SIZE_Y = 125
COLLISION-TYPE = 1
COLLISION-WIDTH = 10
COLLISION-HEIGHT = 80
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 25
COLLISION-WALL = 1

[EXIT]
GAME_MODE-MODE = 1
POSITION-X = 2200
POSITION-Y = 13
DRAW-TEXTURE = "./assets/sprites/cave/cave_out.png"
DRAW-SIZE_X = 50
DRAW-SIZE_Y = 57
COLLISION-TYPE = 1
COLLISION-WIDTH = 50
COLLISION-HEIGHT = 43
COLLISION-OFFSET_X = 0
COLLISION-OFFSET_Y = 30
COLLISION-WALL = 0
WARP-X = 560
WARP-Y = 1750
WARP-SOUND = "./assets/sounds/cave_warp.wav"