[BAT]
DRAW-TEXTURE = "./assets/sprites/character/bat.png"
GAME_MODE-MODE = 1
POSITION-X = 2650
POSITION-Y = 520
VELOCITY-X = 5
VELOCITY-Y = 5
DRAW-SIZE_X = 90
DRAW-SIZE_Y = 30
ANIMATION-STATIC-RECT = [ 0, 0, 61, 64]
ANIMATION-STATIC-X_ADD = 64
ANIMATION-STATIC-NB_FRAME = 5
ANIMATION-STATIC-SPEED = 40000
ANIMATION-LEFT-RECT = [ 0, 0, 61, 64]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 5
ANIMATION-LEFT-SPEED = 40000
ANIMATION-UP-RECT = [ 0, 0, 61, 64]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 5
ANIMATION-UP-SPEED = 40000
ANIMATION-RIGHT-RECT = [ 0, 61, 61, 64]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 5
ANIMATION-RIGHT-SPEED = 40000
ANIMATION-DOWN-RECT = [ 0, 61, 61, 64]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 5
ANIMATION-DOWN-SPEED = 40000
COLLISION-TYPE = 1
COLLISION-WIDTH = 15
COLLISION-HEIGHT = 15
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 0
HEALTH-LIFE = 3
HEALTH-ARMOR = 2
HEALTH-BAR_SIZE_X = 17
HEALTH-BAR_SIZE_Y = 1
INTERACTION_ZONE-RADIUS = 100
DAMAGE-DAMAGE = 1

[BAT]
DRAW-TEXTURE = "./assets/sprites/character/bat.png"
GAME_MODE-MODE = 1
POSITION-X = 2650
POSITION-Y = 370
VELOCITY-X = 5
VELOCITY-Y = 5
DRAW-SIZE_X = 90
DRAW-SIZE_Y = 30
ANIMATION-STATIC-RECT = [ 0, 0, 61, 64]
ANIMATION-STATIC-X_ADD = 64
ANIMATION-STATIC-NB_FRAME = 5
ANIMATION-STATIC-SPEED = 40000
ANIMATION-LEFT-RECT = [ 0, 0, 61, 64]
ANIMATION-LEFT-X_ADD = 64
ANIMATION-LEFT-NB_FRAME = 5
ANIMATION-LEFT-SPEED = 40000
ANIMATION-UP-RECT = [ 0, 0, 61, 64]
ANIMATION-UP-X_ADD = 64
ANIMATION-UP-NB_FRAME = 5
ANIMATION-UP-SPEED = 40000
ANIMATION-RIGHT-RECT = [ 0, 61, 61, 64]
ANIMATION-RIGHT-X_ADD = 64
ANIMATION-RIGHT-NB_FRAME = 5
ANIMATION-RIGHT-SPEED = 40000
ANIMATION-DOWN-RECT = [ 0, 61, 61, 64]
ANIMATION-DOWN-X_ADD = 64
ANIMATION-DOWN-NB_FRAME = 5
ANIMATION-DOWN-SPEED = 40000
COLLISION-TYPE = 1
COLLISION-WIDTH = 15
COLLISION-HEIGHT = 15
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 0
HEALTH-LIFE = 3
HEALTH-ARMOR = 2
HEALTH-BAR_SIZE_X = 17
HEALTH-BAR_SIZE_Y = 1
INTERACTION_ZONE-RADIUS = 100
DAMAGE-DAMAGE = 1

[BOSS]
DRAW-TEXTURE = "./assets/sprites/character/rock_boss.png"
GAME_MODE-MODE = 1
POSITION-X = 2300
POSITION-Y = 200
VELOCITY-X = 5
VELOCITY-Y = 5
DRAW-SIZE_X = 250
DRAW-SIZE_Y = 250
ANIMATION-STATIC-RECT = [ 0, 0, 125, 125]
ANIMATION-STATIC-X_ADD = 125
ANIMATION-STATIC-NB_FRAME = 4
ANIMATION-STATIC-SPEED = 100000
ANIMATION-LEFT-RECT = [ 0, 125, 125, 125]
ANIMATION-LEFT-X_ADD = 125
ANIMATION-LEFT-NB_FRAME = 4
ANIMATION-LEFT-SPEED = 100000
ANIMATION-UP-RECT = [ 0, 375, 125, 125]
ANIMATION-UP-X_ADD = 125
ANIMATION-UP-NB_FRAME = 4
ANIMATION-UP-SPEED = 100000
ANIMATION-RIGHT-RECT = [ 0, 250, 125, 125]
ANIMATION-RIGHT-X_ADD = 125
ANIMATION-RIGHT-NB_FRAME = 4
ANIMATION-RIGHT-SPEED = 100000
ANIMATION-DOWN-RECT = [ 0, 0, 125, 125]
ANIMATION-DOWN-X_ADD = 125
ANIMATION-DOWN-NB_FRAME = 4
ANIMATION-DOWN-SPEED = 100000
COLLISION-TYPE = 1
COLLISION-WIDTH = 15
COLLISION-HEIGHT = 15
COLLISION-OFFSET_X = 10
COLLISION-OFFSET_Y = 10
COLLISION-WALL = 0
HEALTH-LIFE = 25
HEALTH-ARMOR = 5
HEALTH-BAR_SIZE_X = 70
HEALTH-BAR_SIZE_Y = 3
INTERACTION_ZONE-RADIUS = 250
DAMAGE-DAMAGE = 1